// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	dto "d-and-d/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// PublicService is an autogenerated mock type for the PublicService type
type PublicService struct {
	mock.Mock
}

type PublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *PublicService) EXPECT() *PublicService_Expecter {
	return &PublicService_Expecter{mock: &_m.Mock}
}

// GetPublicCharacter provides a mock function with no fields
func (_m *PublicService) GetPublicCharacter() ([]dto.PublicCharacterResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublicCharacter")
	}

	var r0 []dto.PublicCharacterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]dto.PublicCharacterResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []dto.PublicCharacterResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.PublicCharacterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublicService_GetPublicCharacter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicCharacter'
type PublicService_GetPublicCharacter_Call struct {
	*mock.Call
}

// GetPublicCharacter is a helper method to define mock.On call
func (_e *PublicService_Expecter) GetPublicCharacter() *PublicService_GetPublicCharacter_Call {
	return &PublicService_GetPublicCharacter_Call{Call: _e.mock.On("GetPublicCharacter")}
}

func (_c *PublicService_GetPublicCharacter_Call) Run(run func()) *PublicService_GetPublicCharacter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PublicService_GetPublicCharacter_Call) Return(_a0 []dto.PublicCharacterResponse, _a1 error) *PublicService_GetPublicCharacter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PublicService_GetPublicCharacter_Call) RunAndReturn(run func() ([]dto.PublicCharacterResponse, error)) *PublicService_GetPublicCharacter_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicQuest provides a mock function with no fields
func (_m *PublicService) GetPublicQuest() ([]dto.PublicQuestResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublicQuest")
	}

	var r0 []dto.PublicQuestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]dto.PublicQuestResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []dto.PublicQuestResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.PublicQuestResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublicService_GetPublicQuest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicQuest'
type PublicService_GetPublicQuest_Call struct {
	*mock.Call
}

// GetPublicQuest is a helper method to define mock.On call
func (_e *PublicService_Expecter) GetPublicQuest() *PublicService_GetPublicQuest_Call {
	return &PublicService_GetPublicQuest_Call{Call: _e.mock.On("GetPublicQuest")}
}

func (_c *PublicService_GetPublicQuest_Call) Run(run func()) *PublicService_GetPublicQuest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PublicService_GetPublicQuest_Call) Return(_a0 []dto.PublicQuestResponse, _a1 error) *PublicService_GetPublicQuest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PublicService_GetPublicQuest_Call) RunAndReturn(run func() ([]dto.PublicQuestResponse, error)) *PublicService_GetPublicQuest_Call {
	_c.Call.Return(run)
	return _c
}

// NewPublicService creates a new instance of PublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PublicService {
	mock := &PublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
